services:
  openwebui:
    image: ghcr.io/open-webui/open-webui:git-3f3a5bb
    ports:
      - "3000:8080"
    volumes:
      - open-webui:/app/backend/data
    container_name: open-webui
  pipelines:
    image: ghcr.io/open-webui/pipelines:git-ab9012c
    ports:
      - "9099:9099"
    volumes:
      - pipelines:/app/pipelines
    extra_hosts:
      - "host.docker.internal:host-gateway"
    container_name: pipelines
    restart: always
volumes:
  open-webui:
  pipelines: