version: '3'

services:
  traefik:
    image: traefik:v2.10
    command:
      - "--api.insecure=true"
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.transport.lifecycle.gracetimeout=30s"
      - "--ping=true"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - traefik-public
    container_name: traefik
    restart: always

  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    volumes:
      - open-webui:/app/backend/data

    container_name: openwebui
    restart: always
    depends_on:
      - pipelines
    networks:
      - traefik-public
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - PIPELINE_URL=http://pipelines:9099
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.openwebui.rule=PathPrefix(`/`)"
      - "traefik.http.services.openwebui.loadbalancer.server.port=8080"
      - "traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.routers.openwebui.middlewares=sslheader"
  pipelines:
    image: ghcr.io/open-webui/pipelines:main
    # Remove direct port mapping:
    # ports:
    #   - "9099:9099"
    volumes:
      - pipelines:/app/pipelines
    extra_hosts:
      - "host.docker.internal:host-gateway"
    container_name: pipelines
    restart: always
    networks:
      - traefik-public
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pipelines.rule=PathPrefix(`/pipelines`)"
      - "traefik.http.services.pipelines.loadbalancer.server.port=9099"
      - "traefik.http.middlewares.nobuffer.buffering.disable=true"
      - "traefik.http.routers.pipelines.middlewares=nobuffer"
      - "traefik.http.middlewares.strip-pipelines.stripprefix.prefixes=/pipelines"
      - "traefik.http.routers.pipelines.middlewares=strip-pipelines,nobuffer"

networks:
  traefik-public:
    name: traefik-public

volumes:
  open-webui:
  pipelines:

