services:
  openwebui:
    image: ghcr.io/open-webui/open-webui:git-50dec12
    ports:
      - "3000:8080"
    volumes:
      - open-webui:/app/backend/data
    container_name: open-webui
    extra_hosts:
      - "host.docker.internal:host-gateway"
  pipelines:
    image: ghcr.io/open-webui/pipelines:git-dc18bdd
    ports:
      - "9099:9099"
    volumes:
      - pipelines:/app/pipelines
    extra_hosts:
      - "host.docker.internal:host-gateway"
    container_name: pipelines
    restart: always
  tika:
    image: apache/tika:latest-full
    container_name: tika
    ports:
      - "9998:9998"
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
volumes:
  open-webui:
  pipelines: